config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root to: 'books#start'
  get 'start' => 'books#start', as: 'start'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def start

  end
  
  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      # @book = Book.new
      render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
    else
      # @book = Book.find(params[:id])
      render action: :edit
    end
  end

  def destroy
    flash[:notice] = "Book was successfully destroyed"
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
  <% if @book.errors.any? %>
    <div class="error_explantation">
      <div class="error_title">
        <h2>2 errors prohibited this book from being saved:</h2>
      </div>
      <div class="error_content">
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<%= form_with model:@book, local:true do |f| %>
  <div class="actions">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "book_title" %>
  </div>
  <div class="actions">
    <label for="book_body">Body</label>
    <%= f.text_area :body, class: "book_body" %>
  </div>
  <div class="actions">
    <%= f.submit "Update Book"%>
  </div>
  <%= link_to "Show", book_path(@book)%>
  <span>|</span>
  <%= link_to "Back", books_path%>
<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p id = "notice">
    <%= flash[:notice]%>
  </p>
<% end %>
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan = "3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book) %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book_path(book),method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2>New book</h2>
<%= form_with model:@book, local:true do |f| %>
  <% if @book.errors.any? %>
    <div class="error_explantation">
      <div class="error_title">
        <h2>2 errors prohibited this book from being saved:</h2>
      </div>
      <div class="error_content">
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="actions">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "book_title" %>
  </div>
  <div class="actions">
    <label for="book_body">Body</label>
    <%= f.text_area :body, class: "book_body" %>
  </div>
  <div class="actions">
    <%= f.submit "Create Book" %>
  </div>
<% end %>

app/views/books/new.html.erb
<p>Book was duccessfully</p>
<p>
  <strong>Title</strong>
  <%= @book.title %>
  <%= @book.body %>

</p>

app/views/books/show.html.erb
  <% if flash[:notice] %>
    <p id = "notice">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <p>
    <strong>Title: </strong>
    <%= @book.title %>
  </p>
  <p>
    <strong>Body: </strong>
    <%= @book.body %>
  </p>
  <%= link_to "Edit", edit_book_path(@book)%>
  <span>|</span>
  <%= link_to "Back", books_path%>

app/views/books/start.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
<p>
  <%= link_to "start", books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>